### ISSUE TITLE
Make the cards animatable

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-notification#10]
Currently, the cards are directly removed from dom on close which makes them non-animatable.

When closing a card:
1. Mark it as closing with a state attribute and check if it has a CSS animation (for closing) defined
2. If not, remove from dom as currently
3. If yes, add an `animationend` listener for that animation and do the removal only once it triggers

**Comment by jouni** [comment]
Playing devil’s advocate here, but this would be a great addition to `vaadin-overlay` in general, not just for notifications…

**Comment by manolo** [comment]
let's start adding to notifications. If the approach is good we can move to overlay before beta
