### ISSUE TITLE
notification block clicking on element near it, for viewports wider then approx 800px

### ISSUE THREAD

**Issue by Skrikjo** [vaadin/vaadin-notification#103]
### Description
vaadin-notification-card is bigger then notification content, for viewports wider then approx 800px.
and as vaadin-notification-card if transparent it blocks content under it from clicking on it.

### Live Demo
![notificationbug](https://user-images.githubusercontent.com/42034381/55402867-26a24900-555d-11e9-8cac-fa48bd553efc.gif)

### Steps to reproduce
1. create some clickable elements near place where notification will be appeared. For example 100px from edge of notification content(note view port should be wider then 800px)
2. open notification
3. try to click on element that near

### Code example
@Route
public class MainView extends HorizontalLayout {
    int i = 0;

    public MainView(@Autowired MessageBean bean) {
        getElement().setAttribute("style", "justify-content: flex-end; padding-right: 300px;");
        Button button = new Button("Notification");
        button.addClickListener(e -> {
            Notification.show("Test notification", 10000, Notification.Position.TOP_END);
        });

        Button changeText = new Button("Change Text " + i++);
        changeText.addClickListener(e -> changeText.setText("Change Text " + i++));

        add(button, changeText);
    }
}

### Browsers Affected
All

**Comment by web-padawan** [comment]
Can be reproduced with a sampler demo. Use `top-start` notification, then try to click "Styling" tab.

<img width="386" alt="Screenshot 2020-10-13 at 22 45 06" src="https://user-images.githubusercontent.com/10589913/95908565-ea80b300-0da5-11eb-985a-11660eda33e2.png">
