### ISSUE TITLE
Should we change the available values for `horizontalAlign`?

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/vaadin-notification#11]
A lot of participants were intuitively trying to use `left` and `right` values instead of the `start` and `end` in `horizontalAlign`. Were able to come up with the correct way only after reviewing documentation. Should we go back to `left` and `right`?

**Comment by jouni** [comment]
I think we should stick with start and end. It forces developers to be more aware of RTL support. But, we should possibly highlight this in the documentation/examples.
