### ISSUE TITLE
Notification causes other UI items to be unclickable when set to bottom right

### ISSUE THREAD

**Issue by masbaehr** [vaadin/vaadin-notification#116]
Hi, i noticed some issue where notification has a too big container and causes other UI items (outside of the notification) to be unclickable. It seems related to the @media query which i also posted. If i remove those, the container has a proper size.

![image](https://user-images.githubusercontent.com/38694044/54423938-180d0280-4712-11e9-91f8-2cf994056a61.png)

Found a way to fix this in the vaadin-notification-container CSS

Workaround (Not perfect though) - for those who find this issue while it is not fixed
```html
<dom-module id="vaadin-notification-container-fix" theme-for="vaadin-notification-container">
  <template>
     <style>
        :host  {
          flex-direction: row;
        } 
     </style>
  </template>
</dom-module>
<dom-module id="vaadin-notification-card-fix" theme-for="vaadin-notification-card">
  <template>
     <style>
        :host([slot^="middle"])  {
          top: 50%;
        } 
     </style>
  </template>
</dom-module>
```

**Comment by web-padawan** [comment]
Closing as duplicate of #103 which contains an example of how to reproduce the issue with the web component demos.
