### ISSUE TITLE
Consider adding setCloseOnClick

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-notification#119]
Feels like a very common use case that you want the user to be able to dismiss notifications by clicking on them. Not sure how to even do it right now as `getElement().addEventListener("click")` adds the listener to the main element and not `vaadin-notification-card`

**Comment by mvysny** [comment]
Alternatively, please add the close button as it was the case with Vaadin 8.

**Comment by jouni** [comment]
Closed in favor of #129
