### ISSUE TITLE
Keep notification open while the user is interacting with it

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-notification#14]
A new idea came up from DX/UX tests regarding not closing of the notifications. Should we introduce a new functionality that will allow **not** to close the notifications in case of:

1. The notification is hovered with mouse (Along with that add some default styles for hover state)

1. The content of the notification (text) is selected

**Comment by jouni** [comment]
It’s the app designers and developers responsibility to make sure the notifications work for their intended purpose. If they contain the kind of info that the user has to see or be able to copy, they need to make the notifications persistent and not disappear automatically.

I think this would add unnecessary complexity to the implementation for little benefit.
