### ISSUE TITLE
Closing on outside click?

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/vaadin-notification#15]
Should we introduce a way (i.e attribute) for optional enabling `closing on outside click` functionality like we have in `vaadin-overlay`?

**Comment by jouni** [comment]
That’s not how notifications/toasts work, so I think no.

However, the current Notification component in Framework 8 works so, that the notification will stay visible indefinitely until the user does some interaction (mouse move/click, keyboard event) and then starts the duration counter to hide the notification. This is potentially something we could consider as an enhancement.
