### ISSUE TITLE
Consider moving part=content to the card elements

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-notification#30]
Styling the notification card is different from other overlay elements (:host vs [part=”content”]). It’s understandable from the implementation perspective, but for the developer it’s a bit unexpected, and means you can’t use a shared style module for all overlays (not a blocker, but causes some copy-paste code).

**Comment by jouni** [comment]
At the same time, consider removing the named parts for all the different locations (top, bottom, bottom-stretch, etc.). IMO the developer should not care about those, and we should limit the public API, at least initially.

**Comment by jouni** [comment]
The way I would like to see the implementation (current → proposed):
- `vaadin-notification-overlay` → `vaadin-notification-overlay-container`, without `ThemableMixin` (no themable parts, this would be an internal implementation detail)
- `vaadin-notification-card` → `vaadin-notification-overlay`
  - Parts for `overlay` and `content`, just like all other elements that extend `vaadin-overlay`
    - I know technically they are different, but it matches the theme developers mental model a lot better
  - Attributes for the different locations, for styling/theming purposes, e.g. `vaadin-notification-overlay[top-left]`

**Comment by jouni** [comment]
Any reason why you didn’t rename `vaadin-notification-card` → `vaadin-notification-overlay`?

**Comment by platosha** [comment]
@jouni Well, here is what I was thinking like:

- `<vaadin-notification-overlay>` sounds like a subclass of `<vaadin-overlay>` specific for the notification use case. Now that the inheritance was removed for the container element, this name is misleading.
- However, the card is not a subclass of the `<vaadin-overlay>` too. As mentioned above, they are different. Therefore, directly inheriting the card’s the from the overlay’s one is troublesome.
- Instead direct inheriting from the overlay’s theme, theme authors might do better by sharing a style module targeting only the similar parts. However, this has little to do with naming of the elements then, only part names and and structure actually matter.
- The container element, in its turn, has similarities with the `<vaadin-overlay>`’s host, but not the parts.
- Seems like there are both pros and cons for either way. Perhaps we should also consider avoiding `<vaadin-notification-overlay>` name altogether in this scope.

After thinking for a minute or two about this I ended up in less confidence and more doubt. Then just moved on from the element naming question and focused on the rest of the issue: making the parts compatible to enable sharing style modules for theme authors.

**Comment by jouni** [comment]
> Instead direct inheriting from the overlay’s theme, theme authors might do better by sharing a style module targeting only the similar parts. However, this has little to do with the naming of the elements then, only part names and structure actually matter.

Yeah, this should be the recommended approach, that explicit element theme modules include the shared modules (and not the other way around, that shared modules force themselves on multiple element themes). I buy this argument.

Then my question is: does it make sense to have the same parts and structure for the notification card as for overlays? I know I wanted this, but maybe my thinking was a bit biased because I did see notifications and dialogs, for example, similarly.

> Perhaps we should also consider avoiding `<vaadin-notification-overlay>` name altogether in this scope.

That could avoid some confusion. Would `vaadin-notification-container` work fine?

**Comment by platosha** [comment]
> Then my question is: does it make sense to have the same parts and structure for the notification card as for overlays?

It allows for sharing a style module between the notification card and overlays, could be useful for setting background colors and shadows. I don’t see any other benefits.

> That could avoid some confusion. Would `vaadin-notification-container` work fine?

Works for me.

**Comment by jouni** [comment]
If you can get the rest of the team to agree to changing the name, then please implement that :)

As a recap, the elements inside this repo would be:
- `vaadin-notification`: the element used to configure a single notification
- `vaadin-notification-card`: the visible element on screen
- `vaadin-notification-container`: the internal element that handles the positioning of the cards
