### ISSUE TITLE
The notification content is wrapped into two lines in IE11

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-notification#36]
Live demo: https://www.webcomponents.org/element/vaadin/vaadin-notification

![](https://i.imgur.com/zP18VOQ.png)

**Comment by web-padawan** [comment]
I can reproduce this in Chrome and Firefox as well. This is due to the inline demo iframe size.
We could either edit text or use `position="middle"`, personally I would prefer the second option to demonstrate `position` property.
