### ISSUE TITLE
Notification theme variations

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-notification#38]
Other components e.g. `vaadin-button` have color theme variation for *success*, *error*, *contrast*, *primary*, etc. which would be very useful here for semantically different notifications.

**Comment by jouni** [comment]
Yes, this is a clear use case. Before we can implement this, we need a way to pass/teleport the `theme` attribute (and possibly the `class` attribute as well) from the host to the “teleported” `vaadin-notification-card` element.

**Comment by heruan** [comment]
Hope [this](https://goo.gl/VqzWuq) can help 😃

**Comment by heruan** [comment]
Any news about the attribute teleportation? Why isn't it possible to bind the attributes in the usual way, e.g. `[[theme]]` to pass them down the element hierarchy?

**Comment by jouni** [comment]
@heruan, yes, that should be the simplest way to support this use case.

**Comment by jouni** [comment]
Related general issue: https://github.com/vaadin/vaadin-overlay/issues/48

**Comment by heruan** [comment]
Any news about this?

**Comment by adexerivera** [comment]
Is there any news?

**Comment by jouni** [comment]
AFAIK the plan still is to include some built-in variants. We don’t have designs for those yet.

**Comment by jouni** [comment]
Here are the mockups for the variants. They aren’t 100% accurate with the current spacings, but I think we could adjust those closer to what I have here.

<img width="755" alt="notification-variants-light" src="https://user-images.githubusercontent.com/66382/46281116-71271680-c576-11e8-9119-a7b5c4de7173.png">
<img width="755" alt="notification-variants-dark" src="https://user-images.githubusercontent.com/66382/46281118-71271680-c576-11e8-9015-e78deec365eb.png">

I also ended up writing more thorough design guidelines for notifications at the same time. For example, how to handle longer texts and multiple actions/buttons.

Everyone can view the designs in Figma: https://www.figma.com/file/cWX5MdVik2pyoLcy4Qw6EN2s/Notification-component-Lumo-variants?node-id=0%3A1

**Comment by heruan** [comment]
I don't think I'll be able to sleep anymore, as long as these mockups are not ready to use 😃

**Comment by jouni** [comment]
I don’t have a solid idea of how to actually implement these variants, so I ended up prototyping one alternative. Here’s the result https://vaadin-notification-variants.glitch.me and here’s the code https://glitch.com/edit/#!/vaadin-notification-variants?path=index.html

It feels to me that we need to introduce the “actions” slot to be able to nicely align and style the buttons. Also, I didn’t come up with a nice way to detect when there’s a description text, so I ended with an additional `theme=has-description` variant which stacks the buttons vertically.

@platosha might have some other solutions in his pocket?

**Comment by platosha** [comment]
Using a `slot` maybe does not directly apply here, because the template (renderer) content ends up somewhere in a card’s shadow root, where no slotting is happening.

Seems that the prototype uses predefined styles defined for a class. While that works, I think, we should also consider to offer a helper custom element for that use case, e. g., `vaadin-notification-actions`. Thus, chances of a naming and styling collisions would be lower compared to styling a class name.

**Comment by jouni** [comment]
We talked about this yesterday with @tomivirkki. We concluded that we should probably add a new button theme variant for the customized notification buttons and that the general layout should probably be implemented as a feature of `<vaadin-item>` (which has been a plan for a long time).

I would say that my prototype is more just an exercise to see what CSS needs to be applied to get the desired end result and not so much an actual suggestion how it should be implemented.

**Comment by heruan** [comment]
Any update on this? Not sure if it depends on other tickets or it's just not planned yet.

**Comment by tomivirkki** [comment]
We'll most likely target this for Vaadin 14. V13 is quite stacked with upcoming stuff already.

**Comment by moderndeveloperllc** [comment]
@web-padawan You mentioned that the theme attribute is being propagated. But `:host` is still being kept from affecting `vaadin-overlay`? The below is not propagating properly. The `theme` _is_ being set properly, but all the css gets changed to `:host-nomatch` (which could cause issues if I had styles for things other than `vaadin-notification`) in the Shadow DOM.
```
  render() {
    return html`<vaadin-notification theme="${this.type}"
        duration="${this.duration}"
        position="${this.position}">
          <template>
            <div>${this.message}</div>
          </template>
        </vaadin-notification>`;
  }

  static get styles() {
    return [
      css`
          :host([theme="error"]) [part="overlay"] {
            background: red;
            color: #fff;
          }
          :host([theme="success"]) [part="overlay"] {
            background: green;
            color: #fff;
          }
          :host([theme="warning"]) [part="overlay"] {
            background: yellow;
            color: #fff;
          }`,
    ];
  }
```

**Comment by tomivirkki** [comment]
Hi @heruan, all dependencies of V13 should be stable next week so unfortunately this will not make it by then

**Comment by heruan** [comment]
Thanks for the update! I really hope this will be one of the first issues to be tackled down in V14 then 🙂

**Comment by sirbris** [comment]
@jouni how to achieve your (really nice looking!) mockup in java? There are the NotificationVariants but what kind of button styles to use then?

**Comment by platosha** [comment]
@sirbris regular buttons without overrides and a `theme="primary"` button for the primary action should do. The buttons are colorized automatically by the notification styles.

**Comment by sirbris** [comment]
ah, perfect... I also still had old templates defined which interfered. thank you
