### ISSUE TITLE
Notification should have a click listener

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-notification#41]
When the notification is shown in the upper, right corner and says
 "You have 1 new message", you need a click event to be able to show the new email message

**Comment by jouni** [comment]
Workaround: add a click listener for the content element you place inside the notification.

**Comment by johannest** [comment]
Workaround

Extend Vaadin Notification and add following call into it

```
this.getElement()
     .executeJs("window.addEventListener('click', function(){$0.$server.closeNotificationPopup();}, { passive: true , once: true}); ");
```

And also add the following client callable method:

```
@ClientCallable
public void closeNotificationPopup() {
     close();
}
```

**Comment by jouni** [comment]
Combined this and #120 into #128
