### ISSUE TITLE
Notification content should specify min-width

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-notification#44]
With the current default styles, the notification width always spans the entire region it’s placed in. 

Instead, the width of the card should come from the content but never exceed the maximum region width.

**Current:**
<img width="1438" alt="screen shot 2018-01-22 at 10 34 11" src="https://user-images.githubusercontent.com/66382/35211687-354c1a48-ff60-11e7-9380-e2061b12133e.png">

**Expected:**
<img width="1440" alt="screen shot 2018-01-22 at 10 35 52" src="https://user-images.githubusercontent.com/66382/35211700-40c6a1f4-ff60-11e7-9a91-e689c79619f6.png">

**Comment by web-padawan** [comment]
@jouni would it be better to implement this feature in the `theme` styles or the `src` (as part of the unstyled element functionality)?

**Comment by jouni** [comment]
Ideally this could be controlled by a theme. But I would prefer the “expected” behavior as the default.
