### ISSUE TITLE
Adjust the default duration

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-notification#48]
The current default duration is a bit too long

**Comment by samiheikki** [comment]
2750 milliseconds seems to be quite common default duration
https://materialdoc.com/components/snackbars-and-toasts/#duration
https://github.com/material-components/material-components-web/tree/master/packages/mdc-snackbar

**Comment by tomivirkki** [comment]
3000ms was considered too short before: https://github.com/vaadin/vaadin-notification/pull/21/files

Let's try 5s :)
