### ISSUE TITLE
It should be easy to create a notification with text and buttons

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-notification#52]
One of the most common use cases for notifications is to show a message and some accompanying actions, such as `Item deleted  [Undo]` or `Retrying in 15 seconds [Cancel]`.

There are two aspects that we need to make easy:
1. Laying out the content
2. Processing the actions

### For the layout, the simplest way is:
```html
<vaadin-notification>
  <template>
    Item deleted
    <vaadin-button>Undo</vaadin-button>
  </template>
</vaadin-notification>
```

But if the text is longer, the button gets pushed to a new line. To fix that, you’d want to use a flex layout, where the actions are not flexing but the text content is.

```html
<vaadin-notification>
  <template>
    <div style="display: flex;">
      Item deleted
      <vaadin-button>Undo</vaadin-button>
    </div>
  </template>
</vaadin-notification>
```

It’s debatable if we want to utilize vaadin-horizontal-layout here (to avoid custom CSS), or should we introduce some internal slots instead.

```html
<vaadin-notification>
  <template>
    <vaadin-horizontal-layout>
      Item deleted
      <vaadin-button>Undo</vaadin-button>
    </vaadin-horizontal-layout >
  </template>
</vaadin-notification>
```

At least currently, vaadin-horizontal-layout aligns the items to flex-start, so it doesn’t look nice by default. It also requires the text content to be wrapped with an element if you want to use spacing between the button and the text content.

Also, vaadin-button has a default vertical margin, which is also debatable, if we should remove that because it increases the height of the notification unnecessarily.

As an alternative, using slots:
```html
<vaadin-notification>
  <template>
      Item deleted
      <vaadin-button slot="actions">Undo</vaadin-button>
  </template>
</vaadin-notification>
```

This is almost as simple as the simplest example but introduces a bit of internal complexity with the slot. But the slot would allow us to adjust the button styles if needed (like remove the margin), and provide a suitable amount of whitespace between the content and the actions.

### For processing the actions…
…I don’t have good ideas. At least, I think, it should be possible to utilize Polymer data bindings easily or assign an arbitrary JavaScript function for processing the actions using standard DOM APIs.

```html
<vaadin-notification>
  <template>
      Item deleted
      <vaadin-button slot="actions" on-click="_undoDeleteItem">Undo</vaadin-button>
  </template>
</vaadin-notification>
```

```html
<vaadin-notification>
  <template>
      Item deleted
      <vaadin-button slot="actions" action="undo">Undo</vaadin-button>
  </template>
</vaadin-notification>

<script>
  document.querySelector('vaadin-notification').addEventListener('action', (e) => {
    console.log(e.detail); // "undo"
  });
</script>
```

@platosha, thoughts?

**Comment by platosha** [comment]
The named “actoins” slot feature sounds good at first glance. But using a `slot` with a template context does look a bit weird though. Also, the `action` attribute seems a bit weird too, since not defined in the `<vaadin-button>` API.

Should we rather introduce a feature-specific subelement having that slot?

```html
<vaadin-notification>
  <template>
    <vaadin-notification-actor action="undo">
      Item deleted
      <vaadin-button slot="buttons">Undo</vaadin-button>
    </vaadin-notification-actor>
  </template>
</vaadin-notification>
```

In case if introducing another subelement is not what we want, perhaps we should establish a baseline-aligned flex row layout around the users’s template contents out-of-the-box, so that users could do something like:

```html
<vaadin-notification>
  <template>
    <span style="flex: auto;">Item deleted</span>
    <vaadin-button>Undo</vaadin-button>
  </template>
</vaadin-notification>
```

A custom event for action click might be a nice enhancement. Although, at minimum, no special features should be required to catch an action click, AFAIK, since both Polymer and Flow users have workarounds for that already.

**Comment by platosha** [comment]
Would it work to just have something like `display: flex; align-items: baseline; justify-content: space-between;` for the template’s content parent in the card?

**Comment by jouni** [comment]
Hmm, yeah, that could be a nice solution actually. I might go for `align-items: center;` instead, though, since that looks better if there are multiple lines of text in the notification before it.

Center:
<img width="484" alt="screen shot 2018-02-21 at 23 08 13" src="https://user-images.githubusercontent.com/66382/36505426-2976e220-175c-11e8-965b-20b5f0a1a5ea.png">

Baseline:
<img width="479" alt="screen shot 2018-02-21 at 23 08 27" src="https://user-images.githubusercontent.com/66382/36505427-299a3c0c-175c-11e8-9f98-4302fc8baa25.png">

We can also target `::slotted(vaadin-button)` and adjust the margins and disable flexing.

**Comment by jouni** [comment]
The first point can be considered fixed in https://github.com/vaadin/vaadin-notification/commit/1978f75f24481cc66a94823fae981c1bfd754cdc#diff-4304ac9ff933071c409b9d07210142b4R32

I’ll close this issue, we can open another issue if we need some convenience way of adding actions (and their event listeners).
