### ISSUE TITLE
Text is not updated in the shown notification

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-notification#97]
Warning: this bug may be a consequence of the parent where `vaadin-notification` is appended.

Let's assume you have a `div`  in the DOM tree referenced as `div` variable.
(It might be that if you use `body` tag as a value for `div`  then it will work as expected).

Use this code:
```
var notification = document.createElement('vaadin-notification');
var template = document.createElement('template');
notification.appendChild(template);

div.appendChild(notification); // <---- Note: the notification is added to some div

template.innerHTML = "foo";
notification.opened = true;
```

The result: notification is shown, it has text `foo`.
Everything works fine.

Now use this code:
```
template.innerHTML = "bar";
notification.opened = true;
```

The result: notification is shown, it has text `foo`.

Notification should have text `bar` but has text `foo`.

This is unexpected behavior.

**Comment by denis-anisimov** [comment]
Original ticket in flow : https://github.com/vaadin/vaadin-notification-flow/issues/75

**Comment by limonte** [comment]
Unfortunately, templates don't work that way. They are stamped once during the initialization and the update isn't possible.

One way to achieve the dynamic content would be to use renderers:

```js
var notification = document.createElement('vaadin-notification');
document.body.appendChild(notification);

notification.renderer = function(root) {
  root.textContent = 'foo';
};

notification.opened = true;

notification.renderer = function(root) {
  root.textContent = 'bar';
};
```

Live demo: https://butter-pentagon.glitch.me/
Source: https://glitch.com/edit/#!/butter-pentagon?path=index.html:11:0

**Comment by denis-anisimov** [comment]
I guess it doesn't depend whether the notification is attached to the body or any other element (the original bug mentioned that).

So you may close this issue. I've reopened the original ticket in Flow component and referenced your comment from there.

Thanks.

**Comment by limonte** [comment]
> I guess it doesn't depend whether the notification is attached to the body or any other element (the original bug mentioned that).

Correct.

> So you may close this issue. I've reopened the original ticket in Flow component and referenced your comment from there.

Done, thanks!
