### ISSUE TITLE
`open-changed` custom event not implemented

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-notification#99]
### Description
`open-changed` custom event not implemented?

### Expected outcome
According the the API documentation, `vaadin-notification` should fire a `CustomEvent` called `open-changed` when the element is opened or closed.

### Actual outcome
No event is fired.

From what I can see in the code, the `opened-changed` custom event is never fired. This is useful if I want to wait for a close before doing further custom actions.

**Comment by web-padawan** [comment]
Note that correct name is `opened-changed` (name is produced by using `notify: true`), so you have a typo. See the example of using the event listener in the demo:
https://github.com/vaadin/vaadin-notification/blob/5606b67c99e9b6434d7ca70972ccbe4334692efa/demo/notification-sampler-demos.html#L70

Also, API docs are correct https://cdn.vaadin.com/vaadin-notification/1.2.1/#/elements/vaadin-notification

**Comment by moderndeveloperllc** [comment]
@web-padawan Yep. Spent an hour trying to debug because I can't read the docs properly.
